version: '3'
services:
  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PORT=3000
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app:cached
    command: ['npm', 'run', 'dev']

  nginx:
    build: ./nginx
    depends_on:
      - app
    ports:
      - '80:80'
    restart: always

  db:
    build: ./postgres
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - ./postgres/backup:/backup
      - db:/var/lib/postgresql/data

volumes:
  db:
